baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "David's site"
theme = 'loveit'

[params.social]
  [params.social.Mastodon]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "@dawicks"
    # prefix of your social link
    prefix = "https://mastodon.social/"
    # content hovering on the icon
    title = "Mastodon"


[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2