baseURL = 'https://davidwicks.site/'
languageCode = 'en-us'
title = "David's site"
theme = 'loveit'

[menu]
  [[menu.main]]
    name = "About"
    pre = "<i class='fas fa-address-card'></i>"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fas fa-address-card'></i>"
    url = "/projects/"
    weight = 2